### Get item categories list
GET https://jbb-admin.herokuapp.com/api/item-categories

### Get items list 
GET https://jbb-admin.herokuapp.com/api/items?populate=image

### Get a given item
GET https://jbb-admin.herokuapp.com/api/items/1?populate=image

### Get article categories list
GET https://jbb-admin.herokuapp.com/api/article-categories

### Get articles list
GET https://jbb-admin.herokuapp.com/api/articles?populate=%2A

### Get a given article
GET https://jbb-admin.herokuapp.com/api/articles/1?populate=%2A

### Get article image url
GET https://jbb-admin.herokuapp.com/uploads/bb_glow_2a922f8623.jpeg


