### 
@host = http://localhost:1337
@token = abc123

### Get item categories list
GET {{host}}/api/item-categories

### Get items list
GET {{host}}/api/items

### Get items list (with attributes)
GET {{host}}/api/items?populate=%2A&pagination[pageSize]=100

### Get a given item
GET {{host}}/api/items/22?populate=%2A

### Get article categories list
GET {{host}}/api/article-categories

### Get articles list
GET {{host}}/api/articles?populate=%2A&pagination[pageSize]=100

### Get articles list (with attributes) sorted by date
GET {{host}}/api/articles?populate=%2A&sort[0]=createdAt%3Adesc

### Get a given article
GET {{host}}/api/articles/41?populate=%2A




### Feed algolia products search index
GET http://localhost:3000/api/products-index

### Feed algolia articles search index
GET http://localhost:3000/api/articles-index




######## AUTHENTICATION ########
### Create user
POST {{host}}/api/auth/local/register
Content-Type: application/json

{
    "username": "Max",
    "email": "wetsmaxime@gmail.com",
    "password": "max123"
}

### Sign in as a registered user
POST {{host}}/api/auth/local
Content-Type: application/json

{
    "identifier": "wetsmaxime@gmail.com",
    "password": "max123"
}

### Get users
GET {{host}}/api/users/me

### Forgot password
POST {{host}}/api/auth/forgot-password
Content-Type: application/json

{
    "email": "wetsmaxime@gmail.com"
}


### Create comment
POST {{host}}/api/comments
Content-Type: application/json

{
    "data": {
        "ArticleID": 1,
        "AuthorID": 3,
        "Content": "C'est le deuxième commentaire de Maxime sur l'article Botox Botulax"
    }
}

### Update comment
PUT {{host}}/api/comments/1

{
    "data": {
        "Content": "Ceci est une version à nouveau modifiée du premier commentaire de Maxime sur l'article Botox Botulax"
    }
}

### Get comments
GET {{host}}/api/comments

### get filtered comments
GET {{host}}/api/comments?filters[ArticleID][$eq]=14

### get users 
GET {{host}}/api/users
Authorization: Bearer {{token}}

### create sitemap for blog posts
GET http://localhost:3000/blog

