### Get item categories list
GET https://strapi-d6ef.onrender.com/item-categories

### Get items list 
GET https://strapi-d6ef.onrender.com/items

### Get a given item
GET https://strapi-d6ef.onrender.com/items/1

### Get article categories list
GET https://jbb-admin.herokuapp.com/api/article-categories

### Get articles list
GET https://jbb-admin.herokuapp.com/api/articles?populate=%2A

### Get articles list (new)
GET https://strapi-d6ef.onrender.com/articles

### Get a given article
GET https://jbb-admin.herokuapp.com/api/articles/4?populate=%2A

### Get a given article (new)
GET https://strapi-d6ef.onrender.com/articles/4

### Get article image url
GET https://jbb-admin.herokuapp.com/uploads/bb_glow_2a922f8623.jpeg


