### Get item categories list
GET https://jbbeauty-cms.herokuapp.com/api/item-categories

### Get items list
GET https://jbbeauty-cms.herokuapp.com/api/items

### Get items list (with attributes)
GET https://jbbeauty-cms.herokuapp.com/api/items?populate=%2A

### Get a given item
GET https://jbbeauty-cms.herokuapp.com/api/items/1?populate=%2A

### Get article categories list
GET https://jbbeauty-cms.herokuapp.com/api/article-categories

### Get articles list
GET https://jbbeauty-cms.herokuapp.com/api/articles?populate=%2A

### Get a given article
GET https://jbbeauty-cms.herokuapp.com/api/articles/14?populate=%2A




### Feed algolia products search index
GET http://localhost:3000/api/products-index

### Feed algolia articles search index
GET http://localhost:3000/api/articles-index




######## AUTHENTICATION ########
### Create user
POST https://jbbeauty-cms.herokuapp.com/api/auth/local/register
Content-Type: application/json

{
    "username": "Max",
    "email": "wetsmaxime@gmail.com",
    "password": "max123"
}

### Sign in as a registered user
POST https://jbbeauty-cms.herokuapp.com/api/auth/local
Content-Type: application/json

{
    "identifier": "wetsmaxime@gmail.com",
    "password": "max123"
}

### Get users
GET https://strapi-d6ef.onrender.com/users/me
Authorization: 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjQ1MjkwNDAxLCJleHAiOjE2NDc4ODI0MDF9.NZr9FT9ceVD2l6E5cQZi4VJQIlgB8dsqfSDzBfYlV_k'


